cmake_minimum_required(VERSION 3.0)
project(rrpigpio LANGUAGES C VERSION 0.71)

list (APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)

find_package(Threads REQUIRED)
find_package(RT REQUIRED)

option(BUILD_SHARED_LIBS "Create shared libraries" ON)

add_compile_options(-Wall)

# libpigpio.(so|a)
add_library(pigpio pigpio.c command.c custom.cext)

# libpigpiod_if.(so|a)
add_library(pigpiod_if pigpiod_if.c command.c)

# libpigpiod_if2.(so|a)
add_library(pigpiod_if2 pigpiod_if2.c command.c)

# x_pigpio
add_executable(x_pigpio x_pigpio.c)
target_link_libraries(x_pigpio pigpio RT::RT Threads::Threads)

# x_pigpiod_if
add_executable(x_pigpiod_if x_pigpiod_if.c)
target_link_libraries(x_pigpiod_if pigpiod_if RT::RT Threads::Threads)

# x_pigpiod_if2
add_executable(x_pigpiod_if2 x_pigpiod_if2.c)
target_link_libraries(x_pigpiod_if2 pigpiod_if2 RT::RT Threads::Threads)

# pigpiod
add_executable(pigpiod pigpiod.c)
target_link_libraries(pigpiod pigpio RT::RT Threads::Threads)

# pigs
add_executable(pigs pigs.c command.c)
target_link_libraries(pigs Threads::Threads)

# pig2vcd
add_executable(pig2vcd pig2vcd.c command.c)
target_link_libraries(pig2vcd Threads::Threads)

# Configure and install project
include(GenerateExportHeader)
include(CMakePackageConfigHelpers)

generate_export_header(pigpio)

install(TARGETS pigpio pigpiod_if pigpiod_if2 pig2vcd pigpiod pigs
    EXPORT rrpigpioTargets
    LIBRARY  DESTINATION lib${LIB_SUFFIX}
    ARCHIVE  DESTINATION lib${LIB_SUFFIX}
    RUNTIME  DESTINATION bin
    INCLUDES DESTINATION include
)

write_basic_package_version_file(
    "${CMAKE_CURRENT_BINARY_DIR}/rrpigpioConfigVersion.cmake"
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY AnyNewerVersion
)

export(EXPORT rrpigpioTargets
    FILE "${CMAKE_CURRENT_BINARY_DIR}/rrpigpioTargets.cmake"
    NAMESPACE rrpigpio::
)

set(ConfigPackageLocation lib/cmake/rrpigpio)

install(EXPORT rrpigpioTargets
    FILE rrpigpioTargets.cmake
    NAMESPACE rrpigpio::
    DESTINATION ${ConfigPackageLocation}
)

install(
    FILES
        ${CMAKE_CURRENT_LIST_DIR}/cmake/rrpigpioConfig.cmake
        "${CMAKE_CURRENT_BINARY_DIR}/rrpigpioConfigVersion.cmake"
    DESTINATION
        ${ConfigPackageLocation}
)

install(FILES pigpio.h pigpiod_if.h pigpiod_if2.h
    DESTINATION include
    PERMISSIONS OWNER_READ OWNER_WRITE
        GROUP_READ
        WORLD_READ
)

file(GLOB man_1_SRC "*.1")
install(FILES ${man_1_SRC}
    DESTINATION man/man1
    PERMISSIONS OWNER_READ OWNER_WRITE
        GROUP_READ
        WORLD_READ
)

file(GLOB man_3_SRC "*.3")
install(FILES ${man_3_SRC}
    DESTINATION man/man3
    PERMISSIONS OWNER_READ OWNER_WRITE
        GROUP_READ
        WORLD_READ
)

# package project
set(CPACK_PACKAGE_NAME "rrpigpio")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Aaron Spiteri <azzmosphere@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "pigpio library (Ryder Robots fork)
 Unofficial fork of pigpio with BCM2711 fixes.
 Based on pigpio by Joan (joan2937).
 NOT supported by the original author.")
set(CPACK_GENERATOR "DEB")

include(CPack)